import Head from 'next/head'
import { Inter } from 'next/font/google'
import Sidebar from '@component/components/Sidebar'
import Center from '@component/components/Center'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div className='bg-black h-screen overflow-hidden'>
      <Head>
        <title>Spotify 2.0</title>
        <meta name="description" content="Generated by tuan tran" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex">
        <Sidebar />
        <Center />
      </main>
    </div>
  )
}
